# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86081fe4296368db7f70a4897ceebca58e1478b6cfef9ed2766aee79584b377b57d4afc776d2b6547e0ee0bdd6409f9b2f1627a813efde44aa3e0538b9dbc4c1

test:
  secret_key_base: 8438945df85aa3ef8684092adeeb170461239291e93e9de9bef18e778af683107c44425a295183b16dda4b49763a85df44fa6a9daee314a8d89b3268d0514516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
